########################################################################################################################
####                                              DATABASE - Datasource                                             ####
########################################################################################################################

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mybudget_dev #docker container
    username: root
    password:  #beter om in te brengen als environment variabele, of met encryption

########################################################################################################################
####                                           DATABASE - Jpa / Hibernate                                           ####
########################################################################################################################
  jpa:
    show-sql: true  # Show or not log for each sql query, handig tijdens development op de sql statements te zien
