#sql database

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mybudget_dev
    username: mybudget_dev_user
    #    beter om in te brengen als environment variabele, of met encryption
    password: Dev123456!?
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    #    handig tijdens development om de sql statements te zien
    show-sql: true

    #    hibernate generation van schema in de create-target file in het classpath (nog wel ; achter elke lijn te zetten.
    #    Dit is een manier om je schema te laten genereren (vermits hibernate door de ddl-auto: validate geen rechten heeft om dit te doen)
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: mybudget_database_create.sql