# ===============================
# = DATA SOURCE
# ===============================

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mybudget_dev
    username: mybudget_dev_user
    password: Dev123456!?  #beter om in te brengen als environment variabele, of met encryption
    platform: mysql #is deze nodig????
    driver-class-name: com.mysql.cj.jdbc.Driver #moet deze ????

# ===============================
# = JPA / HIBERNATE
# ===============================
  jpa:
    hibernate:
      ddl-auto: create-drop #(create, create-drop, update, validate (tegen productie database).....
      naming: #naming strategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: hibernate.dialect.MySQL5Dialect # Allows Hibernate to generate SQL optimized for a particular DBMS
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true  # Show or not log for each sql query, handig tijdens development op de sql statements te zien