########################################################################################################################
####                                              DATABASE - Datasource                                             ####
########################################################################################################################

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mybudget_prod #docker container
    username: root
    password:  #beter om in te brengen als environment variabele, of met encryption

########################################################################################################################
####                                           DATABASE - Jpa / Hibernate                                           ####
########################################################################################################################
  jpa:
    show-sql: false  # Sonze productie moeten we niet vervuilen met sql statements

